import type { Plan } from "planner-core";

export const samplePlan: Plan = {
  id: "sulphur-springs-100k-2026-default",
  course: {
    id: "sulphur-springs-20k-loop",
    name: "Sulphur Springs 20K Loop",
    loopDistanceM: 20000,
    loopElevationGainM: 365,
    loopElevationLossM: 365,
    aidStations: [
      {
        id: "start-finish",
        name: "Start / Finish (Home Base)",
        distanceMOnLoop: 0,
        elevationM: 260,
        crewAccess: true,
        dropBagAccess: true,
        onCourseProductIds: ["skratch-hydration", "water"],
      },
      {
        id: "aid-1",
        name: "Aid Station 1",
        distanceMOnLoop: 4800,
        elevationM: 146,
        crewAccess: false,
        dropBagAccess: false,
        onCourseProductIds: ["skratch-hydration", "water"],
      },
      {
        id: "aid-2",
        name: "Aid Station 2",
        distanceMOnLoop: 8800,
        elevationM: 184,
        crewAccess: false,
        dropBagAccess: false,
        onCourseProductIds: ["skratch-hydration", "water"],
      },
      {
        id: "aid-3",
        name: "Aid Station 3",
        distanceMOnLoop: 13000,
        elevationM: 206,
        crewAccess: false,
        dropBagAccess: false,
        onCourseProductIds: ["skratch-hydration", "water"],
      },
    ],
    segments: [
      { fromAidId: "start-finish", toAidId: "aid-1", distanceM: 4800, gainM: 57, lossM: 171 },
      { fromAidId: "aid-1", toAidId: "aid-2", distanceM: 4000, gainM: 64, lossM: 26 },
      { fromAidId: "aid-2", toAidId: "aid-3", distanceM: 4200, gainM: 88, lossM: 66 },
      { fromAidId: "aid-3", toAidId: "start-finish", distanceM: 7000, gainM: 156, lossM: 102 },
    ],
  },
  runner: {
    id: "default-runner",
    name: "Runner",
    secPerMeterClimb: 6,
    secPerMeterDescent: 2,
    fluidMlPerHour: 600,
    sodiumMgPerHour: 700,
    carbsGPerHour: 80,
    packCapacityMl: 1500,
  },
  goal: {
    raceId: "sulphur-springs-100k-2026",
    raceName: "Sulphur Springs 100K",
    raceDate: "2026-05-23",
    startTime: "06:00",
    goalFinishTimeSec: 9 * 3600 + 55 * 60,
    loopCount: 5,
  },
  products: [
    {
      id: "skratch-hydration",
      name: "Skratch Labs Hydration Sport Drink Mix",
      type: "drink_mix",
      servingDescription: "500mL flask",
      servingFluidMl: 500,
      carbsG: 19,
      sodiumMg: 400,
      caffeineMg: 0,
    },
    {
      id: "skratch-superfuel",
      name: "Skratch Labs Super High Carb Mix",
      type: "drink_mix",
      servingDescription: "500mL flask",
      servingFluidMl: 500,
      carbsG: 50,
      sodiumMg: 200,
      caffeineMg: 0,
    },
    {
      id: "sis-beta-fuel-gel",
      name: "SiS Beta Fuel Gel",
      type: "gel",
      servingDescription: "1 gel",
      servingFluidMl: 0,
      carbsG: 40,
      sodiumMg: 0,
      caffeineMg: 0,
    },
    {
      id: "carbs-fuel-gel",
      name: "Carbs Fuel Gel",
      type: "gel",
      servingDescription: "1 gel",
      servingFluidMl: 0,
      carbsG: 50,
      sodiumMg: 0,
      caffeineMg: 0,
    },
    {
      id: "neversecond-c30-gel",
      name: "Neversecond C30 Gel",
      type: "gel",
      servingDescription: "1 gel",
      servingFluidMl: 0,
      carbsG: 30,
      sodiumMg: 200,
      caffeineMg: 75,
    },
    {
      id: "xact-bar",
      name: "Xact Energy Bar",
      type: "bar",
      servingDescription: "1 bar",
      servingFluidMl: 0,
      carbsG: 25,
      sodiumMg: 0,
      caffeineMg: 0,
    },
    {
      id: "nerds-clusters",
      name: "Nerds Gummy Clusters",
      type: "candy",
      servingDescription: "16 pieces (~37g)",
      servingFluidMl: 0,
      carbsG: 25,
      sodiumMg: 0,
      caffeineMg: 0,
    },
    {
      id: "water",
      name: "Water",
      type: "water",
      servingDescription: "500mL",
      servingFluidMl: 500,
      carbsG: 0,
      sodiumMg: 0,
      caffeineMg: 0,
    },
  ],
  createdAt: "2026-05-02T00:00:00.000Z",
  updatedAt: "2026-05-02T00:00:00.000Z",
};
